apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-js
spec:
#  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: login-js
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels: # labels to select/identify the deployment
        app: login-js
    spec:     # pod spec
      containers:
      - name: login-js
        image: harbor.k-tech.cloud/msa/login_js:2
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: docker-config-secret
---
apiVersion: v1
kind: Service
metadata:
  name: login-js-service
spec:
  selector:
    app: login-js
  ports:
    - name: login-js
      port: 3000
      targetPort: 3000
  type: ClusterIP
