apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-js
  labels:
    app.kubernetes.io/name: login-js
    app.kubernetes.io/version: v1.76.0
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: login-js
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
        sidecar.istio.io/inject: "true"
      labels:
        # Kiali/Istio가 인식하는 표준 라벨 세트 (한 벌로 충분)
        app: login-js
        version: v1.76.0
        app.kubernetes.io/name: login-js
        app.kubernetes.io/version: v1.76.0
        # (선택) canonical 라벨도 병행 사용 가능
        service.istio.io/canonical-name: login-js
        service.istio.io/canonical-revision: v1.76.0
    spec:
      containers:
        - name: login-js
          image: harbor.k-tech.cloud/msa/login_js:6
          ports:
            - containerPort: 3000
              name: http-loginjs      # ← http- 접두사로 L7 인식
            - containerPort: 9113
              name: http-metrics
      imagePullSecrets:
        - name: docker-config-secret
---
apiVersion: v1
kind: Service
metadata:
  name: login-js-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9113"
spec:
  selector:
    app: login-js          # ← 최소 셀렉터(app만). 주입/버전은 빼기
  ports:
    - name: http-loginjs   # ← 서비스 포트도 http- 접두사
      port: 3000
      targetPort: http-loginjs
    - name: http-metrics
      port: 9113
      targetPort: http-metrics
