apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-pg
spec:
#  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: login-pg
        image: harbor.k-tech.cloud/msa/login_pg:14
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-config-secret
---
apiVersion: v1
kind: Service
metadata:
  name: login-pg-service
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP