apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-js
spec:
#  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: login-js
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      labels: # labels to select/identify the deployment
        app: login-js
        sidecar.istio.io/inject: "true"
        version: v1.76.0
    spec:     # pod spec
      containers:
      - name: login-js
        image: harbor.k-tech.cloud/msa/login_js:6
        ports:
        - containerPort: 3000
        - containerPort: 9113
      imagePullSecrets:
      - name: docker-config-secret
---
apiVersion: v1
kind: Service
metadata:
  name: login-js-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'  # 필요에 따라 수정
    prometheus.io/port: '9113'      # 서비스의 메트릭 포트 번호
    # prometheus.io/probe: 'true'     # 서비스 스크랩 Annotations
spec:
  selector:
    app: login-js
    sidecar.istio.io/inject: "true"
  ports:
    - port: 3000
      name: tcp-loginjs
    - port: 9113
      targetPort: 9113
      name: metrics
