apiVersion: apps/v1
kind: Deployment
metadata:
  name: main
spec:
#  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: main
        image: harbor.k-tech.cloud/msa/main:5
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-config-secret
---
apiVersion: v1
kind: Service
metadata:
  name: main-service
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: main-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - www.k-tech.cloud
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - www.k-tech.cloud
    tls:
      mode: SIMPLE
      credentialName: nginx-secret
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: main-virtualservice
spec:
  gateways:
  - main-gateway
  hosts:
  - www.k-tech.cloud
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: main-service
        port:
          number: 80
