apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-js
spec:
#  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: register-js
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels: # labels to select/identify the deployment
        app: register-js
    spec:     # pod spec
      containers:
      - name: register-js
        image: harbor.k-tech.cloud/msa/register_js:1
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: docker-config-secret
---
apiVersion: v1
kind: Service
metadata:
  name: register-js-service
spec:
  selector:
    app: register-js
  ports:
    - port: 3000
      name: tcp-registerjs
