apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-js
spec:
#  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: nodejs
    spec:     # pod spec
      containers:
      - name: register-js
        image: harbor.k-tech.cloud/kaniko/register_js:2
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: docker-config-secret
---
apiVersion: v1
kind: Service
metadata:
  name: register-js-service
spec:
  selector:
    app: nodejs
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP